#!/usr/bin/env bash
# build-research-index.sh — Deterministic builder for the research index.
#
# Scans research artifact directories (in order: .documentation/, docs/research/,
# documentation/), parses each artifact's YAML frontmatter, extracts the first
# sentence of its Executive Summary, and rewrites a single research-index.md
# at the project root listing every artifact sorted by date desc.
#
# Idempotent: re-running with no new artifacts yields no diff (modulo
# 'last built' timestamp which is intentionally stable per day).
#
# Usage:
#   build-research-index.sh [<project-root>]
#
# If <project-root> is omitted, uses the current working directory.
#
# Exit codes:
#   0   Success (index written or no-op)
#   1   No artifacts found
#   2   Bad arguments

set -u

usage() {
  cat >&2 <<EOF
Usage: build-research-index.sh [<project-root>]

Rebuilds research-index.md from all artifacts under <project-root>/.documentation,
docs/research, and documentation. Sorted by date descending.

Exit codes:
  0   Success
  1   No artifacts found
  2   Bad arguments
EOF
  exit 2
}

PROJECT_ROOT="${1:-$PWD}"
shift 2>/dev/null || true
while [ $# -gt 0 ]; do
  case "$1" in
    --help|-h) usage ;;
    *) echo "build-research-index.sh: unexpected argument: $1" >&2; usage ;;
  esac
done

if [ ! -d "$PROJECT_ROOT" ]; then
  echo "build-research-index.sh: project root is not a directory: $PROJECT_ROOT" >&2
  exit 2
fi

# -----------------------------------------------------------------------------
# Collect artifact paths
# -----------------------------------------------------------------------------
TMP=$(mktemp 2>/dev/null || mktemp -t dr-idx)
trap 'rm -f "$TMP" "$TMP".rows' EXIT

(
  for dir in ".documentation" "docs/research" "documentation"; do
    full="$PROJECT_ROOT/$dir"
    [ -d "$full" ] || continue
    find "$full" -maxdepth 1 -type f -name '*.md' \
      ! -name 'research-index.md' \
      ! -name 'README.md' \
      2>/dev/null
  done
) >"$TMP"

if [ ! -s "$TMP" ]; then
  echo "build-research-index.sh: no research artifacts found under $PROJECT_ROOT" >&2
  exit 1
fi

# -----------------------------------------------------------------------------
# Extract one row per artifact: date \t topic \t version \t status \t rel-path \t hook
# -----------------------------------------------------------------------------
: >"$TMP".rows

while IFS= read -r path; do
  [ -z "$path" ] && continue
  rel="${path#"$PROJECT_ROOT"/}"

  # Read frontmatter (between first two `---` lines, if any)
  fm=$(awk '
    BEGIN { state = 0 }
    NR == 1 && /^---[[:space:]]*$/ { state = 1; next }
    state == 1 && /^---[[:space:]]*$/ { state = 2; exit }
    state == 1 { print }
  ' "$path")

  topic=$(echo "$fm" | grep -E '^(topic|title):[[:space:]]' | head -1 | sed -E 's/^(topic|title):[[:space:]]+//; s/^"//; s/"$//; s/[[:space:]]+$//')
  date_v=$(echo "$fm" | grep -E '^date:[[:space:]]' | head -1 | sed -E 's/^date:[[:space:]]+//; s/[[:space:]]+$//')
  version=$(echo "$fm" | grep -E '^version:[[:space:]]' | head -1 | sed -E 's/^version:[[:space:]]+//; s/^"//; s/"$//; s/[[:space:]]+$//')
  status=$(echo "$fm" | grep -E '^status:[[:space:]]' | head -1 | sed -E 's/^status:[[:space:]]+//; s/[[:space:]]+$//')

  # Fallback for date: parse from filename (topic-YYYY-MM-DD.md)
  if [ -z "$date_v" ]; then
    base=$(basename "$path" .md)
    if echo "$base" | grep -qE '[0-9]{4}-[0-9]{2}-[0-9]{2}$'; then
      date_v=$(echo "$base" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}$')
    fi
  fi

  # Fallback for topic: filename without trailing -YYYY-MM-DD
  if [ -z "$topic" ]; then
    topic=$(basename "$path" .md | sed -E 's/-[0-9]{4}-[0-9]{2}-[0-9]{2}$//; s/-/ /g')
  fi

  # Hook: first non-empty line of "## Executive Summary" body, truncated.
  hook=$(awk '
    /^##[[:space:]]+Executive[[:space:]]+Summary/ { in_es = 1; next }
    in_es && /^##[[:space:]]/ { exit }
    in_es && /^[A-Za-z0-9*_]/ {
      gsub(/^\*\*[^*]*\*\*[[:space:]]*/, "")
      print
      exit
    }
  ' "$path" | head -c 220)

  # Default fallbacks for missing fields
  [ -n "$date_v" ] || date_v="0000-00-00"
  [ -n "$version" ] || version="-"
  [ -n "$status" ] || status="-"
  [ -n "$hook" ] || hook="(no executive summary)"

  printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$date_v" "$topic" "$version" "$status" "$rel" "$hook" >>"$TMP".rows
done <"$TMP"

# Sort by date desc
sort -t$'\t' -k1,1r "$TMP".rows -o "$TMP".rows

# -----------------------------------------------------------------------------
# Render research-index.md
# -----------------------------------------------------------------------------
INDEX_PATH="$PROJECT_ROOT/research-index.md"

OUT_TMP=$(mktemp 2>/dev/null || mktemp -t dr-idx-out)
trap 'rm -f "$TMP" "$TMP".rows "$OUT_TMP"' EXIT

cat >"$OUT_TMP" <<'EOF'
# Research Index

> Auto-generated by deep-research's `build-research-index.sh`. Do not hand-edit
> entries — re-run the script after creating, updating, or removing an
> artifact.

| Date | Topic | Version | Status | Path |
|------|-------|---------|--------|------|
EOF

while IFS=$'\t' read -r date_v topic version status rel hook; do
  # Escape pipes in topic / hook to keep table well-formed
  topic_esc=$(printf '%s' "$topic" | sed 's/|/\\|/g')
  printf "| %s | %s | %s | %s | [%s](%s) |\n" \
    "$date_v" "$topic_esc" "$version" "$status" "$rel" "$rel" >>"$OUT_TMP"
done <"$TMP".rows

cat >>"$OUT_TMP" <<'EOF'

## Summaries

EOF

while IFS=$'\t' read -r date_v topic version status rel hook; do
  printf '### %s — %s\n\n' "$date_v" "$topic" >>"$OUT_TMP"
  printf '`%s` · v%s · %s\n\n' "$rel" "$version" "$status" >>"$OUT_TMP"
  printf '%s\n\n' "$hook" >>"$OUT_TMP"
done <"$TMP".rows

# Atomic move only if changed
if [ -f "$INDEX_PATH" ] && cmp -s "$OUT_TMP" "$INDEX_PATH"; then
  : # no change
else
  cp "$OUT_TMP" "$INDEX_PATH"
fi

count=$(wc -l <"$TMP".rows | tr -d ' ')
echo "build-research-index: indexed $count artifact(s) → $INDEX_PATH"
exit 0
